"""Test password API routes."""

import requests

from flask import url_for
from app import app


def test_password_autogenerator():
    """Test password autogenerator."""
    args = {}
    args['size'] = 4

    with app.test_request_context():
        print(url_for(
            'APIv1_0_0.get_passwords_autogenerated',
            **args,
            _external=True
        ))
        response = requests.get(
            url_for(
                'APIv1_0_0.get_passwords_autogenerated',
                **args,
                _external=True
            ),
            verify=False
        )  # .json()
    assert response.status_code == 200
